-- MBC Portal v2 initial Supabase schema.
-- This normalizes the legacy CodeIgniter/MySQL portal into Postgres tables.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.account_types (
  id bigint generated by default as identity primary key,
  legacy_account_id integer unique,
  name text not null unique,
  role text not null check (role in ('student', 'teacher', 'admin', 'super_admin')),
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_uid integer unique,
  account_type_id bigint references public.account_types(id),
  email text unique,
  first_name text,
  last_name text,
  contact_no text,
  connection_key text,
  inserted_by uuid references public.profiles(id),
  subscription_expires_at timestamptz,
  registered_at timestamptz not null default now(),
  avatar_bucket text,
  avatar_path text,
  status text not null default 'active' check (status in ('active', 'inactive', 'blocked')),
  web_token text,
  android_token text,
  skype_id text,
  time_zone text not null default 'Asia/Kolkata',
  legacy_wp_user text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.groups (
  id bigint generated by default as identity primary key,
  legacy_gid integer unique,
  name text not null,
  price numeric(12,2) not null default 0,
  valid_for_days integer not null default 0,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profile_groups (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  assigned_by uuid references public.profiles(id),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (profile_id, group_id)
);

create table public.custom_form_fields (
  id bigint generated by default as identity primary key,
  legacy_field_id integer unique,
  title text not null,
  field_type text not null default 'text',
  validation_rule text,
  default_value text,
  display_at text not null default 'registration',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profile_custom_fields (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  field_id bigint not null references public.custom_form_fields(id) on delete cascade,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, field_id)
);

create table public.categories (
  id bigint generated by default as identity primary key,
  legacy_cid integer unique,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.levels (
  id bigint generated by default as identity primary key,
  legacy_lid integer unique,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.questions (
  id bigint generated by default as identity primary key,
  legacy_qid integer unique,
  question_type text not null default 'multiple_choice_single',
  body text not null,
  explanation text,
  body_alt text,
  explanation_alt text,
  category_id bigint references public.categories(id),
  level_id bigint references public.levels(id),
  stats_served integer not null default 0,
  stats_correct integer not null default 0,
  stats_incorrect integer not null default 0,
  stats_unattempted integer not null default 0,
  inserted_by uuid references public.profiles(id),
  paragraph text,
  paragraph_alt text,
  parent_question_id bigint references public.questions(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.question_options (
  id bigint generated by default as identity primary key,
  legacy_oid integer unique,
  question_id bigint not null references public.questions(id) on delete cascade,
  option_text text not null,
  option_text_alt text,
  match_text text,
  match_text_alt text,
  score numeric(10,4) not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quizzes (
  id bigint generated by default as identity primary key,
  legacy_quid integer unique,
  name text not null,
  description text,
  starts_at timestamptz,
  ends_at timestamptz,
  duration_minutes integer not null default 10,
  maximum_attempts integer not null default 1,
  pass_percentage numeric(6,2) not null default 50,
  view_answer boolean not null default true,
  camera_required boolean not null default true,
  question_selection_mode text not null default 'manual' check (question_selection_mode in ('manual', 'rule_based')),
  generate_certificate boolean not null default false,
  certificate_text text,
  requires_login boolean not null default true,
  quiz_template text not null default 'default',
  show_chart_rank boolean not null default true,
  quiz_price numeric(12,2) not null default 0,
  ip_address_rule text,
  inserted_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quiz_groups (
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  primary key (quiz_id, group_id)
);

create table public.quiz_users (
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  primary key (quiz_id, profile_id)
);

create table public.quiz_questions (
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  correct_score numeric(10,4) not null default 1,
  incorrect_score numeric(10,4) not null default 0,
  sort_order integer not null default 0,
  primary key (quiz_id, question_id)
);

create table public.quiz_selection_rules (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  category_id bigint references public.categories(id),
  level_id bigint references public.levels(id),
  number_of_questions integer not null,
  correct_score numeric(10,4) not null default 1,
  incorrect_score numeric(10,4) not null default 0,
  created_at timestamptz not null default now()
);

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  legacy_rid integer unique,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'open' check (status in ('open', 'pending', 'pass', 'fail', 'submitted', 'cancelled')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  total_time_seconds integer not null default 0,
  score_obtained numeric(12,4) not null default 0,
  percentage_obtained numeric(8,4) not null default 0,
  attempted_ip inet,
  manual_valuation boolean not null default false,
  photo_bucket text,
  photo_path text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.quiz_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id),
  option_id bigint references public.question_options(id),
  answer_text text,
  score numeric(10,4) not null default 0,
  time_seconds integer not null default 0,
  question_number integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.warning_messages (
  id bigint generated by default as identity primary key,
  attempt_id bigint references public.quiz_attempts(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete cascade,
  warning_at timestamptz not null default now(),
  message text not null
);

create table public.study_materials (
  id bigint generated by default as identity primary key,
  legacy_stid integer unique,
  title text not null,
  description text,
  category_id bigint references public.categories(id),
  created_by uuid references public.profiles(id),
  file_bucket text,
  file_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.study_material_groups (
  study_material_id bigint not null references public.study_materials(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  primary key (study_material_id, group_id)
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category_id bigint references public.categories(id),
  due_at timestamptz,
  created_by uuid references public.profiles(id),
  attachment_bucket text,
  attachment_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assignment_groups (
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  primary key (assignment_id, group_id)
);

create table public.assignment_submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  attachment_bucket text,
  attachment_path text,
  score numeric(10,2),
  status text not null default 'submitted' check (status in ('submitted', 'evaluated', 'returned')),
  submitted_at timestamptz not null default now(),
  evaluated_by uuid references public.profiles(id),
  evaluated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.live_classes (
  id bigint generated by default as identity primary key,
  name text not null,
  initiated_by uuid references public.profiles(id),
  starts_at timestamptz,
  closed_at timestamptz,
  content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.live_class_groups (
  live_class_id bigint not null references public.live_classes(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  primary key (live_class_id, group_id)
);

create table public.live_class_comments (
  id bigint generated by default as identity primary key,
  live_class_id bigint not null references public.live_classes(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.appointment_requests (
  id bigint generated by default as identity primary key,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  requested_to uuid not null references public.profiles(id) on delete cascade,
  appointment_at timestamptz not null default now(),
  time_zone text not null default 'Asia/Kolkata',
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  legacy_pid integer unique,
  profile_id uuid references public.profiles(id) on delete set null,
  group_id bigint references public.groups(id) on delete set null,
  quiz_id bigint references public.quizzes(id) on delete set null,
  amount numeric(12,2) not null default 0,
  paid_at timestamptz,
  gateway text not null default 'manual',
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  transaction_id text,
  other_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payment_submissions (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  student_name text,
  student_id text,
  teacher_name text,
  full_name text,
  installment_label text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  title text,
  message text,
  click_action text,
  target text,
  response text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.notification_recipients (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz,
  primary key (notification_id, profile_id)
);

create table public.social_groups (
  id bigint generated by default as identity primary key,
  legacy_sg_id integer unique,
  name text not null,
  about text,
  status text not null default 'public' check (status in ('public', 'private', 'archived')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.social_group_members (
  social_group_id bigint not null references public.social_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (social_group_id, profile_id)
);

create table public.advertisements (
  id bigint generated by default as identity primary key,
  legacy_add_id integer unique,
  advertisement_code text,
  banner_bucket text,
  banner_path text,
  banner_link text,
  position text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default 'true'::jsonb,
  group_name text not null default 'general',
  sort_order integer not null default 0,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.student_pictures (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  title text,
  file_bucket text,
  file_path text not null,
  uploaded_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.news_feed (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  created_by uuid references public.profiles(id),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.media_assets (
  id bigint generated by default as identity primary key,
  asset_type text not null check (asset_type in ('document', 'audio_book', 'ebook', 'video', 'previous_result', 'image', 'other')),
  title text not null,
  description text,
  file_bucket text,
  file_path text,
  external_url text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.library_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  media_asset_id bigint references public.media_assets(id) on delete set null,
  group_id bigint references public.groups(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'inactive', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index profiles_account_type_idx on public.profiles(account_type_id);
create index profile_groups_group_idx on public.profile_groups(group_id);
create index questions_category_idx on public.questions(category_id);
create index questions_level_idx on public.questions(level_id);
create index question_options_question_idx on public.question_options(question_id);
create index quizzes_inserted_by_idx on public.quizzes(inserted_by);
create index quiz_attempts_profile_idx on public.quiz_attempts(profile_id);
create index quiz_attempts_quiz_idx on public.quiz_attempts(quiz_id);
create index attempt_answers_attempt_idx on public.attempt_answers(attempt_id);
create index payments_profile_idx on public.payments(profile_id);
create index notifications_created_by_idx on public.notifications(created_by);

create trigger account_types_set_updated_at before update on public.account_types for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger groups_set_updated_at before update on public.groups for each row execute function public.set_updated_at();
create trigger custom_form_fields_set_updated_at before update on public.custom_form_fields for each row execute function public.set_updated_at();
create trigger profile_custom_fields_set_updated_at before update on public.profile_custom_fields for each row execute function public.set_updated_at();
create trigger categories_set_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger levels_set_updated_at before update on public.levels for each row execute function public.set_updated_at();
create trigger questions_set_updated_at before update on public.questions for each row execute function public.set_updated_at();
create trigger question_options_set_updated_at before update on public.question_options for each row execute function public.set_updated_at();
create trigger quizzes_set_updated_at before update on public.quizzes for each row execute function public.set_updated_at();
create trigger quiz_attempts_set_updated_at before update on public.quiz_attempts for each row execute function public.set_updated_at();
create trigger study_materials_set_updated_at before update on public.study_materials for each row execute function public.set_updated_at();
create trigger assignments_set_updated_at before update on public.assignments for each row execute function public.set_updated_at();
create trigger assignment_submissions_set_updated_at before update on public.assignment_submissions for each row execute function public.set_updated_at();
create trigger live_classes_set_updated_at before update on public.live_classes for each row execute function public.set_updated_at();
create trigger live_class_comments_set_updated_at before update on public.live_class_comments for each row execute function public.set_updated_at();
create trigger appointment_requests_set_updated_at before update on public.appointment_requests for each row execute function public.set_updated_at();
create trigger payments_set_updated_at before update on public.payments for each row execute function public.set_updated_at();
create trigger social_groups_set_updated_at before update on public.social_groups for each row execute function public.set_updated_at();
create trigger advertisements_set_updated_at before update on public.advertisements for each row execute function public.set_updated_at();
create trigger settings_set_updated_at before update on public.settings for each row execute function public.set_updated_at();
create trigger news_feed_set_updated_at before update on public.news_feed for each row execute function public.set_updated_at();
create trigger media_assets_set_updated_at before update on public.media_assets for each row execute function public.set_updated_at();
create trigger library_items_set_updated_at before update on public.library_items for each row execute function public.set_updated_at();

insert into public.account_types (legacy_account_id, name, role, permissions)
values
  (1, 'Administrator', 'admin', '{
    "users":["add","edit","view","list","list_all","myaccount","remove"],
    "quiz":["attempt","add","edit","view","list","list_all","remove"],
    "results":["view","list","list_all","remove"],
    "questions":["add","edit","view","list","list_all","remove"],
    "setting":["all"],
    "study_material":["add","edit","view","list","list_all","remove"],
    "appointment":["list","list_all"]
  }'::jsonb),
  (2, 'User', 'student', '{
    "users":["myaccount"],
    "quiz":["attempt","view","list"],
    "results":["view","list","remove"],
    "questions":[],
    "study_material":["view","list"],
    "appointment":["list"]
  }'::jsonb),
  (3, 'Super Admin', 'super_admin', '{"all":["all"]}'::jsonb),
  (4, 'Teacher', 'teacher', '{
    "users":["view","list"],
    "quiz":["attempt","add","edit","view","list","list_all"],
    "results":["view","list","list_all"],
    "questions":["add","edit","view","list","list_all"],
    "study_material":["add","edit","view","list","list_all"],
    "assignment":["add","edit","view","list","list_all"],
    "appointment":["list","list_all"]
  }'::jsonb)
on conflict (name) do nothing;

insert into public.groups (legacy_gid, name, price, valid_for_days, description)
values
  (1, 'Free', 0, 0, 'Default free access group'),
  (3, 'Premium-1', 100, 90, 'Premium access group'),
  (4, 'Group 3', 2500, 90, 'Extended access group')
on conflict (legacy_gid) do nothing;

insert into public.levels (legacy_lid, name)
values
  (1, 'Easy'),
  (2, 'Difficult')
on conflict (name) do nothing;

insert into public.settings (key, value, group_name, sort_order, description)
values
  ('portal_name', '"MBC MUMBAI"'::jsonb, 'general', 1, 'Display name for the portal'),
  ('default_time_zone', '"Asia/Kolkata"'::jsonb, 'general', 2, 'Default timezone from the legacy portal'),
  ('default_group_legacy_gid', '1'::jsonb, 'users', 3, 'Legacy default group mapping'),
  ('verify_email', 'true'::jsonb, 'auth', 4, 'Require email verification for new accounts')
on conflict (key) do nothing;

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('portal-uploads', 'portal-uploads', false),
  ('student-submissions', 'student-submissions', false),
  ('quiz-photos', 'quiz-photos', false),
  ('imports', 'imports', false),
  ('library-assets', 'library-assets', true)
on conflict (id) do nothing;

create or replace function public.current_account_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(account_types.role, 'student')
  from public.profiles
  left join public.account_types on account_types.id = profiles.account_type_id
  where profiles.id = auth.uid()
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_account_role() in ('teacher', 'admin', 'super_admin')
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_account_role() in ('admin', 'super_admin')
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_account_type_id bigint;
begin
  select id into default_account_type_id
  from public.account_types
  where role = 'student'
  order by id
  limit 1;

  insert into public.profiles (id, account_type_id, email, first_name, last_name)
  values (
    new.id,
    default_account_type_id,
    new.email,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.account_types enable row level security;
alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.profile_groups enable row level security;
alter table public.custom_form_fields enable row level security;
alter table public.profile_custom_fields enable row level security;
alter table public.categories enable row level security;
alter table public.levels enable row level security;
alter table public.questions enable row level security;
alter table public.question_options enable row level security;
alter table public.quizzes enable row level security;
alter table public.quiz_groups enable row level security;
alter table public.quiz_users enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_selection_rules enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.attempt_answers enable row level security;
alter table public.warning_messages enable row level security;
alter table public.study_materials enable row level security;
alter table public.study_material_groups enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_groups enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.live_classes enable row level security;
alter table public.live_class_groups enable row level security;
alter table public.live_class_comments enable row level security;
alter table public.appointment_requests enable row level security;
alter table public.payments enable row level security;
alter table public.payment_submissions enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_recipients enable row level security;
alter table public.social_groups enable row level security;
alter table public.social_group_members enable row level security;
alter table public.advertisements enable row level security;
alter table public.settings enable row level security;
alter table public.student_pictures enable row level security;
alter table public.news_feed enable row level security;
alter table public.media_assets enable row level security;
alter table public.library_items enable row level security;

create policy "Authenticated users can read roles" on public.account_types for select to authenticated using (true);
create policy "Admins manage roles" on public.account_types for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Users read own profile" on public.profiles for select to authenticated using (id = auth.uid() or public.is_staff());
create policy "Users update own profile" on public.profiles for update to authenticated using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy "Admins insert profiles" on public.profiles for insert to authenticated with check (public.is_admin());
create policy "Admins delete profiles" on public.profiles for delete to authenticated using (public.is_admin());

create policy "Authenticated users read groups" on public.groups for select to authenticated using (true);
create policy "Staff manage groups" on public.groups for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Users read own group memberships" on public.profile_groups for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Staff manage group memberships" on public.profile_groups for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read categories" on public.categories for select to authenticated using (true);
create policy "Staff manage categories" on public.categories for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read levels" on public.levels for select to authenticated using (true);
create policy "Staff manage levels" on public.levels for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read questions" on public.questions for select to authenticated using (true);
create policy "Staff manage questions" on public.questions for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read question options" on public.question_options for select to authenticated using (true);
create policy "Staff manage question options" on public.question_options for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read quizzes" on public.quizzes for select to authenticated using (true);
create policy "Staff manage quizzes" on public.quizzes for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read quiz relations" on public.quiz_groups for select to authenticated using (true);
create policy "Staff manage quiz groups" on public.quiz_groups for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users read assigned quizzes" on public.quiz_users for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Staff manage quiz users" on public.quiz_users for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read quiz questions" on public.quiz_questions for select to authenticated using (true);
create policy "Staff manage quiz questions" on public.quiz_questions for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read quiz rules" on public.quiz_selection_rules for select to authenticated using (true);
create policy "Staff manage quiz rules" on public.quiz_selection_rules for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Users read own attempts" on public.quiz_attempts for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Users create own attempts" on public.quiz_attempts for insert to authenticated with check (profile_id = auth.uid());
create policy "Users update own open attempts" on public.quiz_attempts for update to authenticated using (profile_id = auth.uid() or public.is_staff()) with check (profile_id = auth.uid() or public.is_staff());
create policy "Staff delete attempts" on public.quiz_attempts for delete to authenticated using (public.is_staff());
create policy "Users read own answers" on public.attempt_answers for select to authenticated using (exists (select 1 from public.quiz_attempts qa where qa.id = attempt_id and (qa.profile_id = auth.uid() or public.is_staff())));
create policy "Users insert own answers" on public.attempt_answers for insert to authenticated with check (exists (select 1 from public.quiz_attempts qa where qa.id = attempt_id and qa.profile_id = auth.uid()));
create policy "Staff manage answers" on public.attempt_answers for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users read own warnings" on public.warning_messages for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Users create own warnings" on public.warning_messages for insert to authenticated with check (profile_id = auth.uid());
create policy "Staff manage warnings" on public.warning_messages for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read study material" on public.study_materials for select to authenticated using (true);
create policy "Staff manage study material" on public.study_materials for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read study material groups" on public.study_material_groups for select to authenticated using (true);
create policy "Staff manage study material groups" on public.study_material_groups for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read assignments" on public.assignments for select to authenticated using (true);
create policy "Staff manage assignments" on public.assignments for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read assignment groups" on public.assignment_groups for select to authenticated using (true);
create policy "Staff manage assignment groups" on public.assignment_groups for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users read own submissions" on public.assignment_submissions for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Users create own submissions" on public.assignment_submissions for insert to authenticated with check (profile_id = auth.uid());
create policy "Users update own submissions" on public.assignment_submissions for update to authenticated using (profile_id = auth.uid() or public.is_staff()) with check (profile_id = auth.uid() or public.is_staff());

create policy "Authenticated users read live classes" on public.live_classes for select to authenticated using (true);
create policy "Staff manage live classes" on public.live_classes for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read live class groups" on public.live_class_groups for select to authenticated using (true);
create policy "Staff manage live class groups" on public.live_class_groups for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users read published or own comments" on public.live_class_comments for select to authenticated using (published or profile_id = auth.uid() or public.is_staff());
create policy "Users create own comments" on public.live_class_comments for insert to authenticated with check (profile_id = auth.uid());
create policy "Staff manage live class comments" on public.live_class_comments for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Users read own appointments" on public.appointment_requests for select to authenticated using (requested_by = auth.uid() or requested_to = auth.uid() or public.is_staff());
create policy "Users create own appointments" on public.appointment_requests for insert to authenticated with check (requested_by = auth.uid());
create policy "Users update related appointments" on public.appointment_requests for update to authenticated using (requested_by = auth.uid() or requested_to = auth.uid() or public.is_staff()) with check (requested_by = auth.uid() or requested_to = auth.uid() or public.is_staff());

create policy "Users read own payments" on public.payments for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Staff manage payments" on public.payments for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users create payment submissions" on public.payment_submissions for insert to authenticated with check (profile_id = auth.uid() or profile_id is null);
create policy "Users read own payment submissions" on public.payment_submissions for select to authenticated using (profile_id = auth.uid() or public.is_staff());

create policy "Users read notifications" on public.notifications for select to authenticated using (true);
create policy "Staff manage notifications" on public.notifications for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Users read own notification recipients" on public.notification_recipients for select to authenticated using (profile_id = auth.uid() or public.is_staff());
create policy "Users update own notification recipients" on public.notification_recipients for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy "Staff manage notification recipients" on public.notification_recipients for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Authenticated users read social groups" on public.social_groups for select to authenticated using (true);
create policy "Authenticated users create social groups" on public.social_groups for insert to authenticated with check (created_by = auth.uid() or public.is_staff());
create policy "Owners or staff update social groups" on public.social_groups for update to authenticated using (created_by = auth.uid() or public.is_staff()) with check (created_by = auth.uid() or public.is_staff());
create policy "Users read social memberships" on public.social_group_members for select to authenticated using (true);
create policy "Users manage own social memberships" on public.social_group_members for all to authenticated using (profile_id = auth.uid() or public.is_staff()) with check (profile_id = auth.uid() or public.is_staff());

create policy "Authenticated users read ads" on public.advertisements for select to authenticated using (true);
create policy "Staff manage ads" on public.advertisements for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read settings" on public.settings for select to authenticated using (true);
create policy "Admins manage settings" on public.settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Users read own student pictures" on public.student_pictures for select to authenticated using (profile_id = auth.uid() or uploaded_by = auth.uid() or public.is_staff());
create policy "Users upload own student pictures" on public.student_pictures for insert to authenticated with check (profile_id = auth.uid() or uploaded_by = auth.uid() or public.is_staff());
create policy "Authenticated users read published news" on public.news_feed for select to authenticated using (status = 'published' or public.is_staff());
create policy "Staff manage news" on public.news_feed for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read media assets" on public.media_assets for select to authenticated using (true);
create policy "Staff manage media assets" on public.media_assets for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy "Authenticated users read library items" on public.library_items for select to authenticated using (status = 'active' or public.is_staff());
create policy "Staff manage library items" on public.library_items for all to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "Public avatar and library read access" on storage.objects
for select to public
using (bucket_id in ('avatars', 'library-assets'));

create policy "Authenticated upload access" on storage.objects
for insert to authenticated
with check (bucket_id in ('avatars', 'portal-uploads', 'student-submissions', 'quiz-photos', 'imports', 'library-assets'));

create policy "Owners and staff read private storage" on storage.objects
for select to authenticated
using (
  bucket_id in ('avatars', 'library-assets')
  or public.is_staff()
  or owner = auth.uid()
);

create policy "Owners and staff update storage" on storage.objects
for update to authenticated
using (public.is_staff() or owner = auth.uid())
with check (public.is_staff() or owner = auth.uid());

create policy "Owners and staff delete storage" on storage.objects
for delete to authenticated
using (public.is_staff() or owner = auth.uid());
