create table if not exists public.subject_teachers (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (category_id, teacher_id)
);

alter table public.subject_teachers enable row level security;

drop policy if exists "Staff can view subject teachers" on public.subject_teachers;
create policy "Staff can view subject teachers"
  on public.subject_teachers for select
  using (public.is_staff());

drop policy if exists "Admins can manage subject teachers" on public.subject_teachers;
create policy "Admins can manage subject teachers"
  on public.subject_teachers for all
  using (public.is_admin())
  with check (public.is_admin());
