-- Migration to add attendance tracking

create table public.attendance_records (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  session_date date not null default current_date,
  recorded_at timestamptz not null default now(),
  unique(profile_id, session_date)
);

-- Add RLS policies
alter table public.attendance_records enable row level security;

-- Students can insert their own attendance
create policy "Students can mark own attendance" 
  on public.attendance_records for insert 
  to authenticated 
  with check (profile_id = auth.uid());

-- Students can view their own attendance
create policy "Students can view own attendance" 
  on public.attendance_records for select 
  to authenticated 
  using (profile_id = auth.uid() or public.is_staff());

-- Staff can view all attendance
create policy "Staff can manage all attendance" 
  on public.attendance_records for all 
  to authenticated 
  using (public.is_staff()) 
  with check (public.is_staff());

-- Add a default setting for zoom link if it doesn't exist
insert into public.settings (key, value, group_name, description)
values ('zoom_meeting_link', '"https://zoom.us/j/1234567890"'::jsonb, 'general', 'Default Zoom Meeting Link for classes')
on conflict (key) do nothing;
